#######################################
# Edición del editor de vim	      #
# Autor: A. Lara 		      #
#######################################
set nocompatible

" Show line numbers
set relativenumber

" Blink cursor on error instead of beeping
set visualbell

" Encoding
set encoding=utf-8

" Syntax
syntax enable

" Highlight matching search patterns
set hlsearch

set background=light
colorscheme buttercream
